export const mock_registration = [
  {
    keyboard: 'default',
    label: 'First Name',
    name: 'first_name',
    required: true,
    type: 'input',
  },
  {
    keyboard: 'default',
    label: 'Last Name',
    name: 'last_name',
    required: true,
    type: 'input',
  },
  {
    keyboard: 'default',
    label: 'Birth Date',
    name: 'birth_date',
    required: true,
    type: 'input',
  },
  {
    keyboard: 'default',
    label: 'Email',
    name: 'email',
    required: true,
    type: 'input',
  },
  {
    keyboard: 'numeric',
    label: 'Phone',
    name: 'phone',
    required: false,
    type: 'input',
  },
  // {
  //   keyboard: 'default',
  //   label: 'Country',
  //   name: 'country',
  //   required: true,
  //   type: 'input',
  // },
  // {
  //   keyboard: 'default',
  //   label: 'City',
  //   name: 'city',
  //   required: true,
  //   type: 'input',
  // },
  {
    keyboard: 'default',
    label: 'Password',
    name: 'password',
    required: true,
    type: 'input',
  },
  // {
  //   keyboard: 'default',
  //   label: 'Confirm password',
  //   name: 'confirm_password',
  //   required: true,
  //   type: 'input',
  // },
];
